name: node

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - "dev"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        if [[ "${{ github.ref_name }}" == "dev" ]]; then
          echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          echo "DEPLOY_HOST=${{ secrets.DEV_SERVER_IP }}" >> $GITHUB_ENV
          echo "DEPLOY_KEY=${{ secrets.SSH_PRIVATE_KEY_DEV }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "DEPLOY_ENV=main" >> $GITHUB_ENV
          echo "DEPLOY_HOST=${{ secrets.LIVE_SERVER_IP }}" >> $GITHUB_ENV
          echo "DEPLOY_KEY=${{ secrets.SSH_PRIVATE_KEY_LIVE }}" >> $GITHUB_ENV
        fi

    - name: Deployment
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ secrets.USERNAME || 'ubuntu' }}
        port: ${{ secrets.PORT || 22 }}
        key: ${{ env.DEPLOY_KEY }}
        script: |
          cd /var/www/html/nodejs
          git pull origin ${{ env.DEPLOY_ENV }}
          pm2 restart nodejs --update-env
